lint:
  extends:
    - recommended
  decorators:
    remove-x-internal: on

  rules:
    # https://redoc.ly/docs/cli/built-in-rules/
    info-license: off
    no-empty-servers: off
    info-description: off
    tag-description: off
    operation-4xx-response: off
